### ISSUE TITLE
No reachable servers

### ISSUE THREAD

**Issue by mwettasinghe** [didiercrunch/vulture#2]
I have few mongo data bases in my local machine and mongo is up and running.when i tried to connect via vulture.it says "no reachable servers". but successfully connected to the vulture example server.

Here is my config file

Port: 27017
ServingAddress: 'localhost'
MongoServers:
    -
      name: localhost
      url: localhost:27017

**Comment by didiercrunch** [comment]
Hi there,

there is something wrong in your config file.  The `Port` field is the field the where vulture is running.  You will then access it via `localhost:<Port>`.  Usually, this number is `8000` but the port is already being used I suggest Port `8000 + x` for the smallest workable `x`.  A thing is sure, if you set this port to the same than the one mongo uses `27017` it will not work.   

Bellow a config file where the vulture will listen to port 8765.  Try it if it works better.

didier

```
---
#  The port where the service will run
Port: 8765

#  The address where the service will run.  If you wish to run it on your
#  computer, you should use `localhost`.  If you wish to share the service
#  on your local network, you should use `0.0.0.0`
ServingAddress: 0.0.0.0

#  The list of mongo servers.  Each server is an object with a field *name* that will
#  be shown in the web user interface and a *url* field that points to the mongo server
MongoServers:
    -
      name: localhost
      url: localhost:27017

```

[link to vulture instance when it will run](http://localhost:8765)
